version: "3.1"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://pop:pop@database:5432/pop
    ports:
      - 5050:5050

  database:
    container_name: database
    image: postgis/postgis
    environment:
      POSTGRES_USER: pop
      POSTGRES_PASSWORD: pop
      POSTGRES_DB: pop
    volumes:
      - ./ddl/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./ddl/test-data.sql:/docker-entrypoint-initdb.d/2-data.sql

  adminer:
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
