version: "3.9"

services:
  # fastapi_service:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   hostname: fastapi_service
  #   container_name: fastapi_service
  #   depends_on:
  #     - db_postgres
  #     - redis-cache
  #   ports:
  #     - "5050:5050"
  #   volumes:
  #     - ./:/home/app
  #   networks:
  #     - my-net

  redis-cache:
    image: redis:alpine
    hostname: redis-cache
    container_name: redis-cache
    restart: on-failure
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - cache:/data

  db_postgres:
    image: dolphindatabase/postgis-visiona:1.0.1
    hostname: db_postgres
    container_name: db_postgres
    restart: on-failure
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=pop
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
  
  mycassandra:
    image: cassandra
    container_name: mycassandra
    ports:
      - "9042:9042"
      - "7000:7000"
    volumes:
      - "cassandra-data:/var/lib/cassandra"

volumes:
  db-postgres:
    driver: local

  cache:
    driver: local

  cassandra-data:
    driver: local